#!/bin/bash
#scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source coinlist

for coins in "${coinlist[@]}"; do
    coin=($coins)
        echo ${coin[0]}
        komodo-cli -ac_name=${coin[0]} "${@}"
done
