#!/bin/bash
GR='\033[0;32m'
NC='\033[0m'

printf "\n${GR}>>> CHECKING KOMODO${NC}\n"
cd /home/$USER/komodo/src
git stash
git checkout master
git pull

printf "\n${GR}>>>>>>> CHECKING IGUANA${NC}\n"
cd /home/$USER/dPoW/iguana
git stash
git checkout master
git pull

printf "\n${GR}>>>>>>> CHECKING HUSH3${NC}\n"
cd /home/$USER/hush3
git stash
git checkout hush3
git pull

printf "\n${GR}>>>>>>> CHECKING VERUS${NC}\n"
cd /home/$USER/VerusCoin
git stash
git checkout master
git pull

printf "\n${GR}>>>>>>> CHECKING NANOMSG${NC}\n"
cd /home/$USER/nanomsg
git stash
git checkout master
git pull

printf "\n"
