#!/bin/bash
#
# Common startup for all scripts
#
# @author webworker01
#
#scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
set -euf
#set -euf -o pipefail
#imports
source /home/eclips/.bash_profile
source /home/eclips/install/functions
source /home/eclips/install/repos
source /home/eclips/tools/coinlist

ignoreacs=('VOTE2018' 'VOTE2019' 'BEER' 'PIZZA' 'VRSC' 'HUSH3')

#defaults
addnodes=${addnodes:="-addnode=seed.komodostats.com -addnode=seed.webworker.sh"}
datetime=${datetime:=$(date '+%Y-%m-%d %H:%M:%S')}
dpowseeds=${dpowseeds:=('95.213.238.100' '77.75.121.138' '103.6.12.105' '139.99.209.214')}
